import { useEffect, useState } from 'react'; import { api } from '../api/client';
export default function LdapSettingsPage(){
  const [cfg,setCfg]=useState<any>({}); const [test,setTest]=useState<any>(null); const [users,setUsers]=useState<any[]>([]); const [q,setQ]=useState(''); const [msg,setMsg]=useState('');
  useEffect(()=>{api.get('/admin/ldap/settings').then(r=>setCfg(r.data))},[])
  const save=async()=>{const d=new FormData(); Object.entries(cfg).forEach(([k,v])=>d.append(k,String(v??''))); await api.post('/admin/ldap/settings',d); setMsg('Saved')}
  const search=async()=>setUsers((await api.get('/admin/ldap/search-users',{params:{query:q}})).data)
  const testLogin=async()=>{const u=prompt('LDAP username'); const p=prompt('LDAP password'); if(!u||!p) return; const d=new FormData(); d.append('username',u); d.append('password',p); setTest((await api.post('/admin/ldap/test-login',d)).data)}
  const sync=async(u:any)=>{const d=new FormData(); d.append('username',u.username); d.append('role','signer'); await api.post('/admin/ldap/sync-user',d); alert('Synced')}
  return <div className='space-y-4'><h2 className='text-2xl font-semibold'>LDAP Settings</h2><div className='bg-white border rounded p-4 grid md:grid-cols-2 gap-2'>{Object.keys(cfg).map(k=><input key={k} className='border p-2 rounded' value={String(cfg[k]??'')} onChange={e=>setCfg({...cfg,[k]:e.target.value})} placeholder={k}/>) }<button onClick={save} className='bg-slate-900 text-white px-3 py-2 rounded'>Save</button><button onClick={async()=>setTest((await api.get('/admin/ldap/test')).data)} className='bg-blue-700 text-white px-3 py-2 rounded'>Test Connection</button><button onClick={testLogin} className='bg-indigo-700 text-white px-3 py-2 rounded'>Test Login</button>{msg&&<div className='text-emerald-600'>{msg}</div>}{test&&<pre className='bg-slate-50 p-2 md:col-span-2'>{JSON.stringify(test,null,2)}</pre>}</div><div className='bg-white border rounded p-4'><div className='flex gap-2 mb-2'><input className='border p-2 rounded flex-1' value={q} onChange={e=>setQ(e.target.value)} placeholder='Search LDAP users'/><button onClick={search} className='bg-slate-900 text-white px-3 py-2 rounded'>Search</button></div><div className='space-y-2'>{users.map((u:any)=><div key={u.username} className='border rounded p-2 flex justify-between'><div><div className='font-semibold'>{u.display_name} ({u.username})</div><div className='text-xs'>{u.email}</div></div><button onClick={()=>sync(u)} className='text-blue-600'>Sync</button></div>)}</div></div></div>
}
